title: "Dashboard de Plantilla Pro"
description: "Esta es una plantilla de alto rendimiento diseñada para Jekyll y GitHub Pages."
baseurl: "/Prueba" # Es el nombre de tu repositorio
url: "https://aleja.github.io" # Tu url de GitHub Pages
